version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_prod
    environment:
      POSTGRES_USER: serviceuser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local