version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_prod
    environment:
      POSTGRES_USER: serviceuser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  app:
    build: .
    container_name: order-app
    environment:
      SERVER_PORT: 8088
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: serviceuser
      SPRING_DATASOURCE_PASSWORD: 123456789
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - some-net
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local